swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0

host: localhost:10101
basePath: /web
schemes:
  - http

paths:
  /SalesRep:
    get:
      tags: 
        - SalesRep
      summary: Returns a list of salesreps.
      description: >
         Handler: **be.acme.server.sports.SalesRepHandler**
      produces:
        - application/json
      responses:
        200:
          description: OK
  /SalesRep/{salesRep}:
    get:
      tags: 
        - SalesRep
      parameters:
        - in: path
          name: salesRep
          schema:
            type: string
          required: true
          desscription: SalesRep Id to get
      summary: Returns a single salesrep.
      description: >
         Handler: **be.acme.server.sports.SalesRepHandler**
      produces:
        - application/json
      responses:
        200:
          description: OK          